mermaid
flowchart LR

User[Primární uživatel]

System[Navrhovaný systém
Unified UI + Orchestration + Dashboard]

Fleet[FLEETWARE]
Road[ROAD PLAN]
Pasport[PASPORT]

User --> System
System --> Fleet
System --> Road
System --> Pasport

testn
